#!/usr/bin/env python3
"""Parity test for the Python SKU resolver (Phase 4).

Loads tests/sku_fixtures.json and tests/sku_fixtures_prod.json (the latter
optional, generated by util/audio/generate_sku_fixtures.py). Each fixture
entry has a `type` field that dispatches to the appropriate resolver:

    type='group'      → parse_group_sku(sku) must equal expected
    type='variant'    → parse_variant_sku(sku) must equal expected
    type='round_trip' → format_variant_sku(parse_variant_sku(sku)) must equal sku

The same fixture file is consumed by the JS resolver's parity test —
identical inputs, identical outputs across both implementations.

Run: pytest tests/test_sku_parity.py  (or: python tests/test_sku_parity.py)
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from greenlight.cable_config import (
    parse_group_sku, parse_variant_sku, format_variant_sku,
)


FIXTURES_DIR = Path(__file__).resolve().parent
FIXTURE_FILES = ["sku_fixtures.json", "sku_fixtures_prod.json"]


def load_fixtures():
    """Load every fixture file that exists. Synthetic + (optional) prod."""
    fixtures = []
    for fname in FIXTURE_FILES:
        path = FIXTURES_DIR / fname
        if not path.exists():
            continue
        with open(path) as f:
            fixtures.extend(json.load(f))
    return fixtures


def check_entry(entry):
    """Return None if the fixture passes, or a {expected, actual} dict on failure."""
    sku = entry['sku']
    fix_type = entry.get('type', 'group')  # backwards-compat default

    if fix_type == 'group':
        actual = parse_group_sku(sku)
        expected = entry['expected']
        if actual == expected:
            return None
        return {'expected': expected, 'actual': actual}

    if fix_type == 'variant':
        actual = parse_variant_sku(sku)
        expected = entry['expected']
        if actual == expected:
            return None
        return {'expected': expected, 'actual': actual}

    if fix_type == 'round_trip':
        parsed = parse_variant_sku(sku)
        if parsed.get('kind') is None:
            return {'expected': sku, 'actual': '<parse_variant_sku returned kind=None>'}
        rebuilt = format_variant_sku(
            group_sku=parsed.get('group_sku'),
            prefix=parsed.get('prefix'),
            length=parsed.get('length'),
            connector_code=parsed.get('connector_code'),
        )
        if rebuilt == sku:
            return None
        return {'expected': sku, 'actual': rebuilt}

    return {'expected': '<known type>', 'actual': f'<unknown type: {fix_type!r}>'}


def run_parity_check():
    fixtures = load_fixtures()
    failures = []
    for entry in fixtures:
        result = check_entry(entry)
        if result is None:
            continue
        failures.append({
            'name': entry.get('name', entry['sku']),
            'type': entry.get('type', 'group'),
            'sku': entry['sku'],
            **result,
        })
    return fixtures, failures


def test_sku_parity():
    fixtures, failures = run_parity_check()
    if failures:
        msg_lines = [f"\n{len(failures)}/{len(fixtures)} SKU fixtures failed:"]
        for f in failures:
            msg_lines.append(f"\n  • [{f['type']}] {f['name']}")
            msg_lines.append(f"    sku:      {f['sku']!r}")
            msg_lines.append(f"    expected: {f['expected']}")
            msg_lines.append(f"    actual:   {f['actual']}")
        raise AssertionError('\n'.join(msg_lines))


def main():
    fixtures, failures = run_parity_check()
    loaded = [f for f in FIXTURE_FILES if (FIXTURES_DIR / f).exists()]
    print(f"Loaded {len(fixtures)} fixtures from: {', '.join(loaded)}")
    print()

    if not failures:
        # Per-type breakdown
        by_type = {}
        for entry in fixtures:
            t = entry.get('type', 'group')
            by_type[t] = by_type.get(t, 0) + 1
        breakdown = ', '.join(f"{count} {kind}" for kind, count in sorted(by_type.items()))
        print(f"✅ All {len(fixtures)} fixtures pass ({breakdown})")
        return 0

    print(f"❌ {len(failures)}/{len(fixtures)} fixtures failed:\n")
    for f in failures:
        print(f"  • [{f['type']}] {f['name']}")
        print(f"    sku:      {f['sku']!r}")
        print(f"    expected: {f['expected']}")
        print(f"    actual:   {f['actual']}")
        print()
    return 1


if __name__ == '__main__':
    sys.exit(main())
