/**
 * Parity test for the JS SKU resolver.
 *
 * Loads every fixture file that exists under tests/ — sku_fixtures.json
 * (synthetic edge cases) and sku_fixtures_prod.json (real prod SKUs,
 * generated by util/audio/generate_sku_fixtures.py) — and asserts that
 * shopify_app/app/cable-config.server.js's parseSku matches each entry.
 * Same fixtures are consumed by the Python parity test
 * (tests/test_sku_parity.py). Same input, same output, enforced on both.
 *
 * Run: npm test  (or node --test shopify_app/tests/sku-parity.test.js)
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseSku } from "../app/cable-config.server.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const FIXTURES_DIR = resolve(__dirname, "..", "..", "tests");
const FIXTURE_FILES = ["sku_fixtures.json", "sku_fixtures_prod.json"];

const fixtures = [];
for (const fname of FIXTURE_FILES) {
  const path = resolve(FIXTURES_DIR, fname);
  if (!existsSync(path)) continue;
  fixtures.push(...JSON.parse(readFileSync(path, "utf8")));
}

for (const entry of fixtures) {
  const label = entry.name ?? entry.sku;
  test(label, () => {
    const actual = parseSku(entry.sku);
    assert.deepStrictEqual(
      actual,
      entry.expected,
      `parseSku(${JSON.stringify(entry.sku)}) mismatch`
    );
  });
}
