api_version = "2026-07"

[[extensions]]
name = "Wholesale Order Form"
handle = "wholesale-order-form"
uid = "57804426-b7eb-016c-5223-4204fda867c9a8d2b957"
type = "ui_extension"

[extensions.capabilities]
network_access = true

[[extensions.targeting]]
module = "./src/ReorderPage.jsx"
target = "customer-account.page.render"
